[package]
name = "acts_ks2_collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
xlsxwriter = "0.3.5"
console = "0.14.0"
