[package]
name = "ks2_etl"
version = "1.1.2"
edition = "2021"
build = "build.rs"

[build-dependencies]
winres = "*"

[dependencies]
calamine = "*"
xlsxwriter = "*"
console = "*"
itertools = "*"
# error-chain = "0.12.4"
regex = "*" #используется в load.rs
walkdir = "*"
dialoguer = "*"
