[package]
name = "ks2_etl"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
calamine = "0.18.0"
xlsxwriter = "0.3.5"
console = "0.15.0"
itertools = "0.8.0"
error-chain = "0.12.4"
regex = "1.5.6"
